/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author matheus
 */
public class CastratarCliente extends javax.swing.JPanel {

    /**
     * Creates new form CastratarCliente
     */
    public CastratarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRb_Pfisica = new javax.swing.JRadioButton();
        jRbPessoaJuridica = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTf_Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTF_cpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTF_NomeFantasia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTF_cnpj = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTF_LimiteCredito = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTF_Logradouro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTF_Complemento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTF_Municipio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jCB_Uf = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADASTRO DE CLIENTE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 20, 210, 21);

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(null);

        buttonGroup1.add(jRb_Pfisica);
        jRb_Pfisica.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jRb_Pfisica.setForeground(new java.awt.Color(255, 255, 255));
        jRb_Pfisica.setMnemonic('F');
        jRb_Pfisica.setText("Pessoa Fisica");
        jPanel2.add(jRb_Pfisica);
        jRb_Pfisica.setBounds(18, 33, 119, 24);

        buttonGroup1.add(jRbPessoaJuridica);
        jRbPessoaJuridica.setForeground(new java.awt.Color(255, 255, 255));
        jRbPessoaJuridica.setMnemonic('J');
        jRbPessoaJuridica.setText("Pessoa Juridica");
        jPanel2.add(jRbPessoaJuridica);
        jRbPessoaJuridica.setBounds(208, 33, 132, 24);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 60, 690, 80);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome*:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 150, 60, 17);
        jPanel1.add(jTf_Nome);
        jTf_Nome.setBounds(40, 170, 320, 27);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF*:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 210, 38, 17);
        jPanel1.add(jTF_cpf);
        jTF_cpf.setBounds(40, 230, 320, 27);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome Fantasia*:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(410, 150, 120, 17);
        jPanel1.add(jTF_NomeFantasia);
        jTF_NomeFantasia.setBounds(410, 170, 300, 27);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CNPJ*:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(410, 210, 49, 17);
        jPanel1.add(jTF_cnpj);
        jTF_cnpj.setBounds(410, 230, 300, 27);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Limite de Credito*:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 270, 140, 17);
        jPanel1.add(jTF_LimiteCredito);
        jTF_LimiteCredito.setBounds(40, 290, 210, 27);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Logradouro*:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 340, 100, 17);

        jTF_Logradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_LogradouroActionPerformed(evt);
            }
        });
        jPanel1.add(jTF_Logradouro);
        jTF_Logradouro.setBounds(40, 360, 430, 27);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Numero*:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(510, 340, 80, 20);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(510, 360, 190, 27);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Complemento:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 400, 110, 17);
        jPanel1.add(jTF_Complemento);
        jTF_Complemento.setBounds(40, 420, 430, 27);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bairro*:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(510, 400, 53, 17);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9);
        jTextField9.setBounds(510, 420, 190, 27);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Municipio*:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 460, 80, 17);
        jPanel1.add(jTF_Municipio);
        jTF_Municipio.setBounds(40, 480, 330, 27);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CEP*:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(510, 460, 57, 17);
        jPanel1.add(jTextField11);
        jTextField11.setBounds(510, 480, 190, 27);

        jCB_Uf.setMaximumRowCount(3);
        jCB_Uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jCB_Uf);
        jCB_Uf.setBounds(40, 540, 130, 30);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("UF*:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 520, 50, 17);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tipo de endereço*:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(510, 520, 140, 17);
        jPanel1.add(jTextField12);
        jTextField12.setBounds(510, 540, 190, 27);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Campos \"*\" sao obrigatorios");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(210, 550, 200, 17);

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jLabel16.setText("Adicionar mais endereço");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 680, 220, 20);

        jButton1.setBackground(new java.awt.Color(118, 135, 245));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/disk.png"))); // NOI18N
        jButton1.setMnemonic('S');
        jButton1.setText("Salvar");
        jButton1.setToolTipText("Salva os registros");
        jPanel1.add(jButton1);
        jButton1.setBounds(650, 650, 100, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jTF_LogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_LogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_LogradouroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCB_Uf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRbPessoaJuridica;
    private javax.swing.JRadioButton jRb_Pfisica;
    private javax.swing.JTextField jTF_Complemento;
    private javax.swing.JTextField jTF_LimiteCredito;
    private javax.swing.JTextField jTF_Logradouro;
    private javax.swing.JTextField jTF_Municipio;
    private javax.swing.JTextField jTF_NomeFantasia;
    private javax.swing.JTextField jTF_cnpj;
    private javax.swing.JTextField jTF_cpf;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTf_Nome;
    // End of variables declaration//GEN-END:variables
}
