/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tavv.controle.de.vendas;
import Criptografia.BCrypt;
import Model.ConnectionDataBase;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


import javax.swing.JOptionPane;


/**
 *
 * @author danie
 */
public class Login extends javax.swing.JFrame {

    private ConnectionDataBase bd;
    private Arquivo file;
    private BCrypt BCrypt;
    private Integer cont = 1;
    private String senhaHasheada;
    private Boolean verificaSenha;
    private PreparedStatement statement;
    private ResultSet resultSet;
    private String senhaResultado;
    private static MenuPrincipal telaInicial;
    
    public Login() {
        setResizable(false);  
        bd = new ConnectionDataBase();
	file = new Arquivo();
        this.setLocationRelativeTo(null);
        initComponents();
        
        URL caminhoIcone = getClass().getResource("/icons/icone.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);

        
     
    }
    
    private String AutenticaSenha(String nome, String senhaPassada){
       
         String senhaDoBanco;
      
                        try {
                                                                    if(!bd.getConnection()){
                                                                            JOptionPane.showMessageDialog(null, "Falha na conexão, o sistem será fechado!");
                                                                            System.exit(0);
                                                                    }

                                                                    String url = "SELECT * FROM usuario WHERE nome=?";


                                                                    statement = bd.connection.prepareStatement(url);
                                                                    statement.setString(1, nome);

                                                                    resultSet  = statement.executeQuery();



                                                                      while(resultSet.next()){  
                                                                          senhaDoBanco =  resultSet.getString("senha");


                                                                          verificaSenha= BCrypt.checkpw(senhaPassada, senhaDoBanco);

                                                                        if (verificaSenha){
                                                                            return (senhaDoBanco);
                                                                        }
                                                                      }
                        }catch(Exception erro) {
                                                                        JOptionPane.showMessageDialog(null, "Algo de errado aconteceu:\n " + erro.toString());
                        }
                    
          return ("SENHA ERRADA");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        fieldNome = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        iconeUsuario = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        fieldSenha = new javax.swing.JPasswordField();
        labelUsuario = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        btnSair = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Sistema Tabajara Atacado e Varejo de Vinhos");

        JPanel.setBackground(new java.awt.Color(51, 0, 102));

        fieldNome.setBackground(new java.awt.Color(227, 226, 242));
        fieldNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fieldNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldNome.setBorder(null);
        fieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeActionPerformed(evt);
            }
        });

        btnCadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(51, 0, 51));
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/users.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar-se");
        btnCadastrar.setBorder(null);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEntrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(51, 0, 51));
        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login.png"))); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(null);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        iconeUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_login.png"))); // NOI18N

        labelLogin.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(255, 255, 255));
        labelLogin.setText("Login");

        fieldSenha.setBackground(new java.awt.Color(227, 226, 242));
        fieldSenha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        fieldSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldSenha.setBorder(null);
        fieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSenhaActionPerformed(evt);
            }
        });

        labelUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario.setText("Nome de Usuário: ");

        labelSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(255, 255, 255));
        labelSenha.setText("Senha: ");

        btnSair.setBackground(new java.awt.Color(204, 204, 204));
        btnSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Exit.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setBorder(null);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/black_info.png"))); // NOI18N
        jButton1.setText("INFO");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSenha)
                            .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(JPanelLayout.createSequentialGroup()
                                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(fieldNome)
                                .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelUsuario)))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addComponent(iconeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 118, Short.MAX_VALUE))
            .addGroup(JPanelLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(labelUsuario)
                .addGap(8, 8, 8)
                .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(labelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
     				
     
                
                
                
                
        if((fieldNome.getText().trim().equals("")) && (fieldSenha.getText().trim().equals(""))){
					JOptionPane.showMessageDialog(null, "Verifique se algum campo está vazio!");
				} else {
            
            
                                   senhaResultado = AutenticaSenha(fieldNome.getText(), fieldSenha.getText());
					
                                   try {
						if(!bd.getConnection()){
							JOptionPane.showMessageDialog(null, "Falha na conexão, o sistem será fechado!");
							System.exit(0);
						}
                                                     
						/*String url = "SELECT * FROM usuario WHERE nome=?";
                                                
                                               
						statement = bd.connection.prepareStatement(url);
						statement.setString(1, fieldNome.getText());
                                                
                                                resultSet  = statement.executeQuery();
                                                
                                                    
                                                    
                                                  while(resultSet.next()){  
                                                      senhaHasheada =  resultSet.getString("senha");
                                                      
                                                   
                                                      verificaSenha= BCrypt.checkpw(fieldSenha.getText(), senhaHasheada);
                                                      
                                                    if (verificaSenha){
                                                        System.out.println("SENHA BATE!");
                                                    }
                                                  }
                                                  */
                                                
                                                String userExist = "SELECT * FROM usuario WHERE nome=?";
                                                
                                               
                                                 statement = bd.connection.prepareStatement(userExist);
						 statement.setString(1, fieldNome.getText());
                                                
                                                resultSet  = statement.executeQuery();
                                                 if(resultSet.next()){
                                                                    if("SENHA ERRADA".equals(senhaResultado) && !"".equals(fieldSenha.getText())){

                                                                                      if(cont > 2){
                                                                                                  JOptionPane.showMessageDialog(null, "Senha incorreta! " + cont + " tentativas realizadas!!" );
                                                                                                    if(cont == 6){
                                                                                                            JOptionPane.showMessageDialog(JPanel, "Número de tentativas excedidas!! \nFechando a Aplicação!", "Senha Incorreta", JOptionPane.ERROR_MESSAGE);
                                                                                                            System.exit(0);
                                                                                                    }
                                                                                         cont++;
                                                                                      } 
                                                                                      else{
                                                                                         JOptionPane.showMessageDialog(null, "Senha incorreta!");
                                                                                         cont++;
                                                                                         
                                                                                      }
                                                                     }
                                                                    else if((fieldSenha.getText().trim().equals(""))){
                                                                        JOptionPane.showMessageDialog(null, "Verifique o campo de senha!");
                                                                    }
                                                                    else{

                                                                    String url2 = "SELECT * FROM usuario WHERE nome=? AND senha=?";
                                                                            

                                                                   statement = bd.connection.prepareStatement(url2);
                                                                   statement.setString(1, fieldNome.getText());
                                                                   statement.setString(2, senhaResultado);

                                                                  resultSet  = statement.executeQuery();

                                                                    if(resultSet.next()){

                                                                                          String nome = resultSet.getString("nome");
                                                                                          file.escreverArquivo(nome);

                                                                                          JOptionPane.showMessageDialog(null, "Usuario logado com sucesso \n Nome: " + nome);
                                                                                          MenuPrincipal mp = new MenuPrincipal ();
                                                                                              Login lg = new Login ();
                                                                                              lg.dispose();

                                                                                  } 
                                                                                  
                                                                    }
                                                 }else {
                                                    JOptionPane.showMessageDialog(JPanel, "Nenhum usuário com esse username foi encontrado!", "Usuário Inexistente", JOptionPane.ERROR_MESSAGE);
                                                    
                                                 }
						resultSet.close();
						statement.close();
						bd.close();
                                                
                                                 
					} catch(Exception erro) {
						JOptionPane.showMessageDialog(null, "Algo de errado aconteceu:\n " + erro.toString());
					}
					
				}
    }//GEN-LAST:event_btnEntrarActionPerformed

    
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
          Cadastro cad = new Cadastro ();
		cad.setSize(600, 594);
                cad.setLocationRelativeTo(null);
		cad.setVisible(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void fieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSenhaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      JOptionPane.showMessageDialog(null, "Tabajara Atacado e Varejo de Vinhos, Todos os Direitos Reservados, 2018.");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JPasswordField fieldSenha;
    private javax.swing.JLabel iconeUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables


}
